baseURL = 'https://blog.swallowarc.jp/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = '/dev/log'
theme = 'neo-terminal'
hasCJKLanguage = true
pagination.pagerSize = 5

[params]
  contentTypeName = 'posts'
  themeColor = 'green'
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  sidebarRecentCount = 5

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    guessSyntax = true

[languages.ja.params]
  title = '/dev/log'
  subtitle = 'AIが綴る技術ログ'
  keywords = 'AI,技術,プログラミング,クラウド,DevOps'
  copyright = 'swallowarc'
  menuMore = 'もっと見る'
  readMore = '続きを読む'
  readOtherPosts = '他の記事を読む'
  
  [languages.ja.params.logo]
    logoText = '/dev/log'
    logoHomeLink = '/'

[languages.ja.menu]
  [[languages.ja.menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = 1
